# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        lfs: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install -U ddtrace
      env:
        DD_TAG: step-test-tag

    - name: Test with pytest
      run: |
        export DD_CIVISIBILITY_AGENTLESS_ENABLED=true
        export DD_API_KEY=${{ secrets.DD_API_KEY }}
        export DD_SITE=us5.datadoghq.com
        export DD_ENV=ci
        export DD_SERVICE=my-python-app
        pytest --ddtrace

    - name: add datadog tags
      run: |
        export DD_API_KEY=${{ secrets.DD_API_KEY }}
        export DD_SITE=us5.datadoghq.com
        export DD_ENV=ci
        export DD_SERVICE=my-python-app
        export DD_TAGS=team:ci
        
        npm install -g @datadog/datadog-ci
        datadog-ci tag --level pipeline

  static-analysis:
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: my-python-app
        dd_env: ci
        dd_site: us5.datadoghq.com
        cpu_count: 2  


  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check imported libraries are secure and compliant
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: my-python-app
        dd_env: ci
        dd_site: us5.datadoghq.com

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'QA'
    steps:
      - name: deploy to QA
        run: |
          echo "deploy to QA"


